version: "2"
volumes:
  influxdb_data:
      driver: local
  chronograf_data:
      driver: local
  kapacitor_data:
      driver: local
  grafana_data:
      driver: local
services:
  influxdb:
    image: xiocode/influxdb
    ports:
      - "18083:8083"
      - "18086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb/
    networks:
      - back-tier
  telegraf:
    image: xiocode/telegraf
    depends_on:
      - influxdb
    ports:
      - "18092:8092"
      - "18094:8094"
      - "18125:8125"
    volumes:
      - ./telegraf/:/etc/telegraf/
    networks:
      - back-tier
    command:
      - "telegraf"
      - "-config"
      - "/etc/telegraf/telegraf.conf"
      - "-config-directory"
      - "/etc/telegraf/telegraf.d"
  kapacitor:
    image: xiocode/kapacitor
    depends_on:
      - influxdb
    ports:
      - "19092:9092"
    volumes:
      - kapacitor_data:/var/lib/kapacitor/
      - ./kapacitor/:/etc/kapacitor/
    command:
      - "kapacitord"
      - "-config"
      - "/etc/kapacitor/kapacitor.conf"
    networks:
      - back-tier
  chronograf:
    image: xiocode/chronograf
    depends_on:
      - influxdb
    ports:
      - "18000:10000"
    environment:
      CHRONOGRAF_BIND: 0.0.0.0:10000
      CHRONOGRAF_LOCAL_DATABASE: /data/chronograf.db
    volumes:
      - chronograf_data:/data/
      - ./chronograf/:/etc/chronograf/
    networks:
      - front-tier
      - back-tier
  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - "13000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
