version: "2"
volumes:
  influxdb_data:
      driver: local
services:
  influxdb:
    image: nexia/influxdb
    ports:
      - "9083:8083"
      - "9086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb/
  telegraf:
    image: nexia/telegraf
    depends_on:
      - influxdb
    volumes:
      - .:/etc/telegraf/
    command:
      - "telegraf"
      - "-config"
      - "/etc/telegraf/telegraf.conf"
      - "-config-directory"
      - "/etc/telegraf/telegraf.d"
